package com.acalendar.acal.amazonaws.mobile.api;

//
//  CloudLogicAPIFactory.java
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.10
//

/**
 * Produces instances of Cloud Logic API configuration.
 */
public class CloudLogicAPIFactory {

    private CloudLogicAPIFactory() {}

    /**
     * Gets the configured micro-service instances.
     * @return
     */
    public static CloudLogicAPIConfiguration[] getAPIs() {
        final CloudLogicAPIConfiguration[] apis = new CloudLogicAPIConfiguration[] {
                new CloudLogicAPIConfiguration("LambdaMicroservice",
                                              "Created by AWS Lambda",
                                              "https://84kwqa3pde.execute-api.us-west-2.amazonaws.com/prod",
                                              new String[] {
                                                  "/login",
                                                  "/signup",
                                                  "/rejectFriend",
                                                  "/addFriend",
                                                  "/getFriends",
                                                  "/acceptFriend",
                                                  "/createEvent",
                                                  "/getEvents",
                                              },
                                              com.acalendar.acal.amazonaws.mobile.api.id84kwqa3pde.LambdaMicroserviceClient.class),
        };

        return apis;
    }
}
