//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.10
//
package com.acalendar.acal.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 4be31414-597c-4d6e-8a02-0210cae381d1 aws-my-sample-app-android-v0.10";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:269ebfce-a76d-48c1-9130-5c3f1422548e";
    // AMAZON MOBILE ANALYTICS
    public static final String  AMAZON_MOBILE_ANALYTICS_APP_ID =
        "7cb03816b62949b1b2019395e1272ffa";
    // Amazon Mobile Analytics region
    public static final Regions AMAZON_MOBILE_ANALYTICS_REGION = Regions.US_EAST_1;
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "acalendar-userfiles-mobilehub-1275254137";
    // S3 BUCKET REGION
    public static final Regions AMAZON_S3_USER_FILES_BUCKET_REGION =
        Regions.fromName("us-west-2");
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("us-west-2");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_I1JfvnDC7";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "5u13mbhcen2h722j889t1iigeo";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "13hgt7m0rpup8pqmrvagc0eed45rehndnorqldn6gcpdourb8g2j";
}
