package util.table;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import model.MessageCategory;

/**
 * Each instance of this class represents a row in the messages table
 *
 */
@DynamoDBTable(tableName = "messages")
public class MessagesTableClass {

    /**
     * Id of the message
     * Generated by DynamoDBMapper automatically
     * (a UUID)
     */
    private String messageId;

    /**
     * The category of the message
     */
    private String messageCategory;

    /**
     * Time of creation of an entry in the message table
     * stored as a string
     */
    private String createdAt;

    /**
     * User that triggered creation of this entry in the table
     * (a UUID string)
     */
    private String createdByUid;

    /**
     * With which event is this message associated
     */
    private String eventId;

    /////////////////////////////////////////////////////////////////
    /////                getters and setters                   //////
    /////////////////////////////////////////////////////////////////

    public String getMessageCategory() {
        return messageCategory;
    }

    public void setMessageCategory(MessageCategory messageCategory) {
        this.messageCategory = messageCategory.toString();
    }

    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getCreatedByUid() {
        return createdByUid;
    }

    public void setCreatedByUid(String createdByUid) {
        this.createdByUid = createdByUid;
    }

    public String getEventId() {
        return eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

}
