package util.table;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import model.MessageCategory;

@DynamoDBTable(tableName = "message")
public class MessageTableClass {

    /**
     * Id of the message
     * Generated by DynamoDBMapper automatically
     * (a UUID)
     */
    private String messageId;

    /**
     * The category of the message
     */
    private MessageCategory messageCategory;

    /**
     * Time of creation of an entry in the message table
     * stored as a string
     */
    private String createdAt;

    /**
     * User that triggered creation of this entry in the table
     * (a UUID string)
     */
    private String createdByUid;

    /**
     * With which event is this message associated
     */
    private String eventId;




}
